-- 8장: 업무 관리 시스템 공통 스키마 생성
-- 실행: psql -X -v ON_ERROR_STOP=1 -h localhost -U task_admin \
--   -d task_management -W -f examples/08_create_schema.sql
\set ON_ERROR_STOP on

BEGIN;

CREATE TABLE department (
    department_id bigint GENERATED BY DEFAULT AS IDENTITY,
    department_code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT department_pk PRIMARY KEY (department_id),
    CONSTRAINT department_code_uq UNIQUE (department_code),
    CONSTRAINT department_name_uq UNIQUE (name),
    CONSTRAINT department_code_format_ck
        CHECK (department_code ~ '^[A-Z][A-Z0-9_]*$'),
    CONSTRAINT department_name_not_blank_ck CHECK (btrim(name) <> '')
);

CREATE TABLE app_user (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY,
    department_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    email varchar(254) NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deactivated_at timestamptz,
    CONSTRAINT app_user_pk PRIMARY KEY (user_id),
    CONSTRAINT app_user_email_uq UNIQUE (email),
    CONSTRAINT app_user_department_fk FOREIGN KEY (department_id)
        REFERENCES department (department_id) ON DELETE RESTRICT,
    CONSTRAINT app_user_name_not_blank_ck CHECK (btrim(name) <> ''),
    CONSTRAINT app_user_email_basic_ck
        CHECK (email = lower(email) AND position('@' IN email) > 1),
    CONSTRAINT app_user_active_time_ck CHECK (
        (is_active AND deactivated_at IS NULL)
        OR (NOT is_active AND deactivated_at IS NOT NULL)
    )
);

CREATE TABLE project (
    project_id bigint GENERATED BY DEFAULT AS IDENTITY,
    project_code varchar(20) NOT NULL,
    manager_user_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    description text,
    status varchar(20) NOT NULL DEFAULT 'planned',
    start_date date NOT NULL,
    end_date date,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_pk PRIMARY KEY (project_id),
    CONSTRAINT project_code_uq UNIQUE (project_code),
    CONSTRAINT project_manager_fk FOREIGN KEY (manager_user_id)
        REFERENCES app_user (user_id) ON DELETE RESTRICT,
    CONSTRAINT project_code_format_ck
        CHECK (project_code ~ '^[A-Z][A-Z0-9_]*$'),
    CONSTRAINT project_name_not_blank_ck CHECK (btrim(name) <> ''),
    CONSTRAINT project_status_ck CHECK (
        status IN ('planned', 'active', 'on_hold', 'completed', 'cancelled')
    ),
    CONSTRAINT project_date_order_ck
        CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT project_updated_order_ck CHECK (updated_at >= created_at)
);

CREATE TABLE project_member (
    project_id bigint NOT NULL,
    user_id bigint NOT NULL,
    member_role varchar(20) NOT NULL DEFAULT 'member',
    joined_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_member_pk PRIMARY KEY (project_id, user_id),
    CONSTRAINT project_member_project_fk FOREIGN KEY (project_id)
        REFERENCES project (project_id) ON DELETE RESTRICT,
    CONSTRAINT project_member_user_fk FOREIGN KEY (user_id)
        REFERENCES app_user (user_id) ON DELETE RESTRICT,
    CONSTRAINT project_member_role_ck
        CHECK (member_role IN ('manager', 'member', 'viewer'))
);

CREATE TABLE task (
    task_id bigint GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    parent_task_id bigint,
    created_by bigint NOT NULL,
    assignee_id bigint,
    title varchar(200) NOT NULL,
    description text,
    status varchar(20) NOT NULL DEFAULT 'todo',
    priority varchar(20) NOT NULL DEFAULT 'medium',
    start_date date,
    due_date date,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamptz,
    CONSTRAINT task_pk PRIMARY KEY (task_id),
    CONSTRAINT task_project_fk FOREIGN KEY (project_id)
        REFERENCES project (project_id) ON DELETE RESTRICT,
    CONSTRAINT task_parent_fk FOREIGN KEY (parent_task_id)
        REFERENCES task (task_id) ON DELETE RESTRICT,
    CONSTRAINT task_creator_fk FOREIGN KEY (created_by)
        REFERENCES app_user (user_id) ON DELETE RESTRICT,
    CONSTRAINT task_assignee_fk FOREIGN KEY (assignee_id)
        REFERENCES app_user (user_id) ON DELETE RESTRICT,
    CONSTRAINT task_title_not_blank_ck CHECK (btrim(title) <> ''),
    CONSTRAINT task_status_ck CHECK (
        status IN ('todo', 'in_progress', 'blocked', 'done', 'cancelled')
    ),
    CONSTRAINT task_priority_ck
        CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    CONSTRAINT task_date_order_ck
        CHECK (due_date IS NULL OR start_date IS NULL OR due_date >= start_date),
    CONSTRAINT task_parent_not_self_ck
        CHECK (parent_task_id IS NULL OR parent_task_id <> task_id),
    CONSTRAINT task_updated_order_ck CHECK (updated_at >= created_at),
    CONSTRAINT task_completed_time_ck CHECK (
        (status = 'done' AND completed_at IS NOT NULL)
        OR (status <> 'done' AND completed_at IS NULL)
    )
);

CREATE TABLE task_comment (
    comment_id bigint GENERATED BY DEFAULT AS IDENTITY,
    task_id bigint NOT NULL,
    author_id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz,
    CONSTRAINT task_comment_pk PRIMARY KEY (comment_id),
    CONSTRAINT task_comment_task_fk FOREIGN KEY (task_id)
        REFERENCES task (task_id) ON DELETE RESTRICT,
    CONSTRAINT task_comment_author_fk FOREIGN KEY (author_id)
        REFERENCES app_user (user_id) ON DELETE RESTRICT,
    CONSTRAINT task_comment_content_not_blank_ck CHECK (btrim(content) <> ''),
    CONSTRAINT task_comment_updated_order_ck
        CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE task_history (
    history_id bigint GENERATED BY DEFAULT AS IDENTITY,
    task_id bigint NOT NULL,
    changed_by bigint NOT NULL,
    event_type varchar(30) NOT NULL,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    changed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT task_history_pk PRIMARY KEY (history_id),
    CONSTRAINT task_history_task_fk FOREIGN KEY (task_id)
        REFERENCES task (task_id) ON DELETE RESTRICT,
    CONSTRAINT task_history_changer_fk FOREIGN KEY (changed_by)
        REFERENCES app_user (user_id) ON DELETE RESTRICT,
    CONSTRAINT task_history_event_not_blank_ck CHECK (btrim(event_type) <> ''),
    CONSTRAINT task_history_details_object_ck
        CHECK (jsonb_typeof(details) = 'object')
);

COMMIT;

\dt
