-- 9장: 재실행 가능한 CRUD 연습
-- 모든 변경은 마지막 ROLLBACK으로 취소됩니다.
\set ON_ERROR_STOP on
\pset pager off

BEGIN;

INSERT INTO department (department_code, name)
VALUES ('LAB', '기술연구팀')
RETURNING department_id, department_code, name;

INSERT INTO task_comment (task_id, author_id, content)
SELECT t.task_id, u.user_id, 'CRUD 실습용 임시 댓글입니다.'
FROM task t
JOIN project p ON p.project_id = t.project_id
CROSS JOIN app_user u
WHERE p.project_code = 'PORTAL'
  AND t.title = '화면 설계'
  AND u.email = 'haneul.kim@example.test'
RETURNING comment_id, task_id, author_id, content;

UPDATE task
SET priority = 'urgent',
    updated_at = TIMESTAMPTZ '2026-08-04 15:00:00+09'
WHERE title = '화면 설계'
  AND project_id = (SELECT project_id FROM project WHERE project_code = 'PORTAL')
RETURNING task_id, title, priority, updated_at;

INSERT INTO department (department_code, name)
VALUES ('LAB', '디지털연구팀')
ON CONFLICT (department_code) DO UPDATE
SET name = EXCLUDED.name
RETURNING department_id, department_code, name;

DELETE FROM task_comment
WHERE content = 'CRUD 실습용 임시 댓글입니다.'
RETURNING comment_id, content;

CREATE TEMP TABLE truncate_practice (
    practice_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note text NOT NULL
);

INSERT INTO truncate_practice (note) VALUES ('첫 행'), ('둘째 행');
TRUNCATE TABLE truncate_practice RESTART IDENTITY;
INSERT INTO truncate_practice (note) VALUES ('초기화 뒤 첫 행');
SELECT practice_id, note FROM truncate_practice;

ROLLBACK;

\pset pager on
